#include <bits/stdc++.h>
using namespace std;

int main()
{
    pair<int,int> vect1={90,89};
    cout<<vect1.first<<" "<<vect1.second<<endl;

    /////////////////////////////////////////////////////////////////////////////////////////////

    pair<int,int> vect2{78,67};
    cout<<vect2.first<<" "<<vect2.second<<endl;

    ///////////////////////////////////////////////////////////////////////////////////////////

    pair<int, string> p;
    p = make_pair(2, "abc"); // 1st way of giving values
    cout << p.first << " " << p.second << endl;

    p = {7, "zxc"}; // 2nd way of giving values
    cout << p.first << " " << p.second << endl;

    pair<int, string> p1 = p; // pair can be copy from one pair to other pair
    pair<int, string> &p2 = p; // Here p2 and p are same pairs with different names are generated by referential operator
    cout << p1.first << " " << p1.second << endl;

    pair<int, string> p9;
    cin>>p9.first>>p9.second; // taking input from user
    cout<<p9.first<<" "<<p9.second<<endl;

    // Array of Pairs
    pair<int,int> ar_p[4]; //First Array operation
    ar_p[0]={1 ,11};
    ar_p[1]={2,22};
    ar_p[2]={3,33};
    ar_p[3]={4,44};
    for(int i=0;i<4;i++)
    {
        cout<<ar_p[i].first<<" "<<ar_p[i].second<<endl;
    }

    pair<int,int> pro[5];//Second Operation
    for(int i=0;i<5;i++)
    {
        pro[i].first=i;
        pro[i].second=i*i;
    }
    for(int i=0;i<5;i++)
    {
        cout<<pro[i].first<<" "<<pro[i].second<<endl;
    }

    // only one value input
    pair<int,string> pin;
    cin>>pin.first;
    cout<<pin.first;

    return 0;
}


// 90 89
//78 67
// 2 abc
// 7 zxc
// 7 zxc
// 56 nlkn
// 56 nlkn
// 1 11   
// 2 22   
// 3 33
// 4 44
// 0 0
// 1 1
// 2 4
// 3 9
// 4 16
// 88
// 88